vpc_cidr                = "10.0.0.0/16"
project_name            = "teste-ilia"
region                  = "us-east-1"
ssh_key_name            = "my-ssh-key"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones      = ["us-east-1a", "us-east-1b"]
k8s_version             = "1.32"
node_desired_size       = 2
node_max_size           = 3
node_min_size           = 1
node_instance_type      = ["t3.medium"]
disk_size               = 20
