variable "project_name" {}
variable "cluster_role_arn" {}
variable "k8s_version" {}
variable "subnet_ids" {}
variable "security_group_ids" {}
variable "node_role_arn" {}
variable "node_desired_size" {}
variable "node_max_size" {}
variable "node_min_size" {}
variable "instance_types" {}
variable "disk_size" {}
variable "ssh_key_name" {}